### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by yeoniii20** [SUNNY-PJ/Frontend#35]
# Todo

> 2024.08.30 ~

### chat

- [x] Create a chat room
- [x] Delete chat room
- [x] View chat contents
- [x] Chat with users who are your friends
- [x] Chat with users who aren't your friends
- [x] Enter chat room from profile
