### ISSUE TITLE
Update API

### ISSUE THREAD

**Issue by yeoniii20** [SUNNY-PJ/Frontend#38]
# Todo

> change and update api

### Friends

- [x] 친구 목록 조회
- [x] 친구 신청
- [x] 친구 승인
- [x] 친구 거절
- [x] 친구 삭제

### Competition

- [x] 대결 상태 확인
- [x] 대결 신청
- [x] 대결 승인
- [x] 대결 거절
- [x] 대결 목록 조회
- [x] 대결 포기
