### ISSUE TITLE
v1.5.0

### ISSUE THREAD

**Issue by yeoniii20** [SUNNY-PJ/Frontend#41]
#Todo

- [ ] 이전 대화 내용 조회 api 수정 후 반영
- [ ] 안읽음 표시 api 수정 후 반영 (2일 경우 1로 표시하고 있음)
- [ ] 채팅방 나갈 때 소켓 연결 해제 확인
- [ ] 채팅방 삭제 시 상대방도 채팅방 삭제 되는 지 확인
- [ ] 프로필에서 친구 신청 시, 친구 상태 확인
- [ ]
